#!/bin/sh

SVCONF=/etc/supervisord.conf

cp /etc/supervisord.conf.templ $SVCONF
for i in /data/*
do
	if [ -e "$i/etc/fetchmailrc" ]; then
            CONF=$(basename $i)
	    cat << EOF >>$SVCONF

[program:$CONF]
environment=FETCHMAILHOME=$i/etc
command=/usr/bin/fetchmail $FETCHMAIL_OPTS -d 300 --nodetach --syslog
stderr_logfile = syslog
stdout_logfile = syslog
EOF
            chown fetchmail:fetchmail $i/etc
            chown fetchmail:fetchmail $i/etc/fetchmailrc
            chmod 0600 $i/etc/fetchmailrc
            rm $i/etc/fetchmail.pid
        fi
done

mkdir /data/log 2>/dev/null
chown fetchmail.fetchmail /data/log
chown fetchmail.fetchmail $SVCONF

rm /tmp/supervisor.sock 2>/dev/null

