#!/bin/sh

SVCONF=/etc/supervisord.conf
FETCHMAILBASE=/var/lib/fetchmail.d

function addconfig {
    RCCONFIG=$1
    CONF=$2

    echo addconfig $RCCONFIG as $CONF

    FMRC=$FETCHMAILBASE/$CONF/fetchmailrc

    mkdir -p $FETCHMAILBASE/$CONF
    cp $RCCONFIG $FMRC

    chown fetchmail:fetchmail $FETCHMAILBASE/$CONF
    chown fetchmail:fetchmail $FMRC

	cat << EOF >>$SVCONF

[program:$CONF]
environment=FETCHMAILHOME=$FETCHMAILBASE/$CONF
command=/usr/bin/fetchmail $FETCHMAIL_OPTS -d 300 --nodetach --syslog
stderr_logfile = syslog
stdout_logfile = syslog
EOF
    chmod 0600 $FMRC
}

echo "init fetchmailrc"

rm -rf $FETCHMAILBASE
mkdir -p $FETCHMAILBASE
cp /etc/supervisord.conf.templ $SVCONF

for i in /data/*
do
	if [ -e "$i/etc/fetchmailrc" ]; then
        CONF=$(basename $i)
        addconfig $i/etc/fetchmailrc $CONF
    fi
done

for i in $(find /data -name "*.fetchmailrc")
do
    CONF=$(basename $i .fetchmailrc)
    addconfig $i $CONF
done

mkdir /data/log 2>/dev/null
chown fetchmail.fetchmail /data/log
chown fetchmail.fetchmail $SVCONF

rm /tmp/supervisor.sock 2>/dev/null

